Merge branch 'main' into add-innotronic-track-hardware

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,7 +1,6 @@
 name: Publish release
 
 on:
-  workflow_dispatch:
   push:
     tags:
       - v**
@@ -10,6 +9,52 @@ env:
   UV_NO_SOURCES: true
 
 jobs:
+  test:
+    uses: ./.github/workflows/test.yml
+
+  pypi:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+      - name: get version
+        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+      - name: build and publish
+        env:
+          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+        run: |
+          uv build
+          uv publish
+      - name: Fetch milestone notes
+        run: uv run fetch_milestone.py ${GITHUB_REF_NAME#v} > release_notes.md || true
+      - name: Create GitHub release entry
+        uses: softprops/action-gh-release@v2
+        with:
+          draft: true
+          prerelease: false
+          name: ${{ env.VERSION }}
+          tag_name: ${{ env.VERSION }}
+          body_path: release_notes.md
+      - name: verify
+        shell: bash
+        run: |
+          for i in {1..100}; do
+            if python -m pip install "feldfreund_devkit==${VERSION#v}"; then
+              echo "Successfully installed feldfreund_devkit version ${VERSION#v}"
+              break
+            else
+              echo "Attempt $i failed. Retrying in 2 seconds..."
+              sleep 2
+            fi
+          done
+
+          if [ $i -eq 100 ]; then
+            echo "Failed to install feldfreund_devkit after 100 attempts"
+            exit 1
+          fi
+
   docs:
     name: Build and publish docs
     runs-on: ubuntu-latest
@@ -27,15 +72,3 @@ jobs:
         uses: JamesIves/github-pages-deploy-action@v4.7.3
         with:
           folder: site
-      - name: Fetch milestone notes
-        run: uv run fetch_milestone.py ${GITHUB_REF_NAME#v} > release_notes.md || true
-      - name: Create GitHub release entry
-        uses: softprops/action-gh-release@v2
-        with:
-          draft: true
-          prerelease: false
-          name: ${{ github.ref_name }}
-          tag_name: ${{ github.ref_name }}
-          body_path: release_notes.md
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
